#ifdef __cplusplus
extern "C" {
#endif

#ifndef STEADQ_H
#define STEADQ_H

/* Warning: this header is generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result codes matching the spec exit codes.
 */
#define STEADQ_OK 0

#define STEADQ_NOT_COMMITTED 1

#define STEADQ_INDETERMINATE 2

#define STEADQ_CORRUPTION 3

#define STEADQ_RESOURCE_EXHAUSTED 4

#define STEADQ_PERMISSION_DENIED 5

#define STEADQ_IO_FAILURE 6

#define STEADQ_UNSUPPORTED 64

/**
 * Opaque lease handle. Not thread-safe; use from one thread at a time.
 */
typedef struct SteadqLease SteadqLease;

/**
 * Opaque payload reader handle. Not thread-safe.
 */
typedef struct SteadqPayloadReader SteadqPayloadReader;

/**
 * Opaque queue handle. Safe to share across C threads.
 */
typedef struct SteadqQueue SteadqQueue;

/**
 * Job ID (128 bits = 16 bytes).
 */
typedef struct SteadqJobId {
  uint8_t bytes[16];
} SteadqJobId;

/**
 * Get last error as a C string. Returns pointer to thread-local storage.
 * The pointer is valid until the next SteadQ call on the same thread.
 * Do not free.
 */
const char *steadq_last_error(void);

/**
 * After steadq_lease, steadq_ack, steadq_retry, or steadq_bury returns
 * STEADQ_INDETERMINATE, the transition ticket as JSON for steadq_resolve.
 * Returns NULL when the last such call left no ticket, and after an
 * indeterminate steadq_enqueue, which has no transition ticket. Thread-local;
 * valid until the next steadq_enqueue, steadq_lease, steadq_ack,
 * steadq_retry, or steadq_bury on the same thread, so it may be passed
 * straight into steadq_resolve. Do not free.
 */
const char *steadq_last_ticket_json(void);

/**
 * No-op for ABI compatibility: steadq_last_error() returns thread-local
 * storage that does not need to be freed.
 */
void steadq_free_string(const char *_s);

/**
 * Query the ABI version.
 */
unsigned int steadq_abi_version(void);

/**
 * Initialize a new queue. Returns null on failure.
 */
struct SteadqQueue *steadq_init(const char *path, unsigned int shard_count);

/**
 * Open an existing queue. Returns null on failure.
 */
struct SteadqQueue *steadq_open(const char *path);

/**
 * Close a queue handle.
 */
void steadq_close(struct SteadqQueue *queue);

/**
 * Enqueue a job.
 */
int steadq_enqueue(struct SteadqQueue *queue,
                   const uint8_t *payload,
                   size_t payload_len,
                   const char *content_type,
                   unsigned int max_attempts,
                   struct SteadqJobId *job_id_out);

/**
 * Lease a job.
 */
int steadq_lease(struct SteadqQueue *queue,
                 uint64_t lease_duration_ns,
                 struct SteadqLease **lease_out);

/**
 * See steadq.h for documentation.
 */
int steadq_lease_verify(struct SteadqQueue *queue, struct SteadqLease *lease);

/**
 * See steadq.h for documentation.
 */
int steadq_ack(struct SteadqQueue *queue, struct SteadqLease *lease);

/**
 * See steadq.h for documentation.
 */
int steadq_retry(struct SteadqQueue *queue, struct SteadqLease *lease);

/**
 * See steadq.h for documentation.
 */
int steadq_bury(struct SteadqQueue *queue, struct SteadqLease *lease, unsigned int reason);

/**
 * Run a recovery pass.
 */
int steadq_recover(struct SteadqQueue *queue);

/**
 * Free a lease handle.
 */
void steadq_lease_free(struct SteadqLease *lease);

/**
 * Get the job ID from a lease handle.
 */
void steadq_lease_job_id(const struct SteadqLease *lease, struct SteadqJobId *out);

/**
 * Get the generation from a lease handle.
 */
uint64_t steadq_lease_generation(const struct SteadqLease *lease);

/**
 * Get the attempt from a lease handle.
 */
unsigned int steadq_lease_attempt(const struct SteadqLease *lease);

/**
 * Get the payload length from a lease handle.
 */
uint64_t steadq_lease_payload_length(const struct SteadqLease *lease);

/**
 * Copy the boot_id from a lease handle into `out`.
 * Writes a NUL-terminated string. `out_len` is the buffer capacity.
 */
int steadq_lease_boot_id(const struct SteadqLease *lease, char *out, size_t out_len);

/**
 * Copy the content type from a lease handle into `out`.
 * Writes a NUL-terminated string. `out_len` is the buffer capacity.
 */
int steadq_lease_content_type(const struct SteadqLease *lease, char *out, size_t out_len);

/**
 * Copy the source path from a lease handle into `out`.
 * Writes a NUL-terminated string. `out_len` is the buffer capacity.
 */
int steadq_lease_source_path(const struct SteadqLease *lease, char *out, size_t out_len);

/**
 * Open a verified payload reader for a lease. The payload is hashed once.
 * Returns STEADQ_OK and sets *reader_out on success.
 * The caller must free the reader with steadq_reader_free.
 */
int steadq_lease_open_reader(struct SteadqQueue *queue,
                             const struct SteadqLease *lease,
                             struct SteadqPayloadReader **reader_out);

/**
 * Read payload bytes at the given offset.
 * Sets *bytes_read_out to bytes read (0 at EOF).
 */
int steadq_reader_read(const struct SteadqPayloadReader *reader,
                       uint8_t *buf,
                       size_t buf_len,
                       uint64_t offset,
                       size_t *bytes_read_out);

/**
 * Return the total payload length in bytes.
 */
uint64_t steadq_reader_payload_len(const struct SteadqPayloadReader *reader);

/**
 * Free a payload reader handle.
 */
void steadq_reader_free(struct SteadqPayloadReader *reader);

/**
 * Resolve an indeterminate operation from a ticket. The ticket is provided
 * as JSON bytes. If stabilize is non-zero, the resolver attempts to complete
 * any pending barriers. Returns STEADQ_OK on successful resolution.
 */
int steadq_resolve(struct SteadqQueue *queue,
                   const uint8_t *ticket_json,
                   size_t ticket_len,
                   int stabilize);

#endif  /* STEADQ_H */

#ifdef __cplusplus
}
#endif
